name: khj
description: My Flutter Portfolio Project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.23.12

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_storage_web: ^3.6.4
  flutter_localization: ^0.1.14
  go_router: ^9.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.11
  bloc: ^8.1.4
  stream_transform: ^2.1.0
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/adaptive/
    - assets/ttw/
    - assets/srreport/
    - assets/clips/
    - assets/gllim/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
          style: normal
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
          style: normal
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR/NotoSansKR-Light.ttf
        - asset: fonts/NotoSansKR/NotoSansKR-Regular.ttf
          style: normal
        - asset: fonts/NotoSansKR/NotoSansKR-Bold.ttf
          weight: 700
          
flutter_intl:
  enabled: true
